---
kind: pipeline
name: linux-pipeline-jdk17
type: docker

image_pull_secrets:
  - dockerconfig

platform:
  os: linux
  arch: amd64

steps:
  - name: restore-cache
    image: meltwater/drone-cache:v1.1.0
    pull: always
    volumes:
      - name: jdk17m2cache
        path: /drone/src/.repo
    settings:
      cache_key: "{{ .Repo.Owner }}_{{ .Repo.Name }}_{{ .Commit.Branch }}_{{ checksum \"pom.xml\" }}"
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      bucket: maven-it-extension-build-cache
      region: eu-central-1
      restore: true
      filesystem-cache-root: /drone/src
      mount:
        - .repo

  - name: mavenjdk17
    pull: always
    image: docker.io/maven:3.8.4-openjdk-17-slim
    volumes:
      - name: jdk17m2cache
        path: /drone/src/.repo
    commands:
      - mvn -Dmaven.repo.local=/drone/src/.repo -V clean verify --fail-at-end --batch-mode

  - name: rebuild-cache
    image: meltwater/drone-cache:v1.1.0
    pull: always
    volumes:
      - name: jdk17m2cache
        path: /drone/src/.repo
    settings:
      cache_key: "{{ .Repo.Owner }}_{{ .Repo.Name }}_{{ .Commit.Branch }}_{{ checksum \"pom.xml\" }}"
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      bucket: maven-it-extension-build-cache
      region: eu-central-1
      rebuild: true
      filesystem-cache-root: /drone/src
      mount:
        - .repo
      when:
        event: push

volumes:
  - name: jdk17m2cache
    temp: { }
