= Cross Assembler Linker Relocator (CrALinkR)
Karl Heinz Marbaise; {docdate}
:author: Karl Heinz Marbaise
:appendix-number:
:sectnums:
:sectlinks:
:xrefstyle: full
:toc:
//:toc: left


= Overview

Idea of the project...


== Expressions

You can define a lot of expressions apart from the usual mathematical
operations like addition, subtraction, division and multiplication.

You can the hexadecimal notation like `$1000` or `$1000_1000` where `_`
is only for better reading.

You can use the octal notation like `0o7123` or `0o712_333` where `_` is
only for better reading.

You can use the binary notation like `0b10000000` or `0b1000_0000`.

You can use the modulo operation like `1024%16`.

You can combine all operations for example like this:

`1_024 + 35/7+3*$1000+0b1000_0000 % $10 + 0o1234_567`


== Example

* `.db` define byte (8 bit)
* `.dw` define word (16 bit)
* `.dw` define quad word (32 bit)

=== 6502
The following shows the source code of a 6502 based assembly file.

[source]
.first.???
----
; Starting..
    .cpu   C6502
;
ZP_START1   .equ    $00
FOR_STACK2  .equ    ZP_START1+4
STACK       .equ    $2000
;
memory_one: .ds 2 ; 2 Byte
memory_two: .ds 2 ; 2 Byte
;
    .org    $1000

start: .cseg

    LDA #$10
    STA memory_one
    LDA memory_two

    lda     STACK+1,x
    cmp     #$81
    lda     STACK+2,x

    .org $c000
text:   .db "This is a text"

----

=== 8085


[source]
.first.???
----
; Starting..
    .cpu   8085
;
ZP_START1   .equ    $0000
STACK       .equ    ZP_START1+$100
;
memory_one: .ds 2 ; 2 Byte
memory_two: .ds 2 ; 2 Byte
;
    .org    $1000

start: .cseg

    MVI A,$10
    STA MEMORY_ONE
    LXI B,memory_two

    .org $c000
text:   .db "This is a text"

----

Encoding for source files is UTF-8.


== TODO's

We could implement things like:

* `hi(expression)` (higher 8 bit's)
* `lo(expression)` (lower 8 bit's)
* `hiw(expression)` (higher 16 bit's)
* `low(expression)` (lower 16 bit's)
